### ISSUE TITLE
Error when accessing video

### ISSUE THREAD

**Issue by 7h3ju57** [learningit/plugin.video.hgtv.canada#1]
Im trying to watch house of bryan and season 1 - 2 work fine but when i try to play season 3 i get this error.

15:10:18 T:7292   DEBUG: Clearing cached fileitems [plugin://plugin.video.hgtv.canada/?mode=GE&name=House%20of%20Bryan&url=64724547710]
15:10:18 T:7292   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.hgtv.canada/?mode=GE&name=House%20of%20Bryan&url=64724547710)
15:10:18 T:7292   DEBUG:   ParentPath = [plugin://plugin.video.hgtv.canada/]
15:10:18 T:1676   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin HGTV Canada('plugin://plugin.video.hgtv.canada/','7','?mode=GE&name=House%20of%20Bryan&url=64724547710')
15:10:18 T:1676   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the HGTV Canada (id=29) plugin...
15:10:18 T:7720  NOTICE: Thread LanguageInvoker start, auto delete: false
15:10:18 T:7720    INFO: initializing python engine.
15:10:18 T:7720   DEBUG: CPythonInvoker(29, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): start processing
15:10:18 T:7720  NOTICE: -->Python Interpreter Initialized<--
15:10:18 T:7720   DEBUG: CPythonInvoker(29, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): the source file to load is "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py"
15:10:18 T:7720   DEBUG: CPythonInvoker(29, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): setting the Python path to C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada;D:\Program Files (x86)\Kodi\system\python\DLLs;D:\Program Files (x86)\Kodi\system\python\Lib;D:\Program Files (x86)\Kodi\python27.zip;D:\Program Files (x86)\Kodi\system\python\lib\plat-win;D:\Program Files (x86)\Kodi\system\python\lib\lib-tk;D:\Program Files (x86)\Kodi;D:\Program Files (x86)\Kodi\system\python;D:\Program Files (x86)\Kodi\system\python\lib\site-packages
15:10:18 T:7720   DEBUG: CPythonInvoker(29, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): entering source directory C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada
15:10:18 T:7720   DEBUG: CPythonInvoker(29, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): instantiating addon using automatically obtained id of "plugin.video.hgtv.canada" dependent on version 2.1.0 of the xbmc.python api
15:10:18 T:7292   DEBUG: ------ Window Init (DialogBusy.xml) ------
15:10:23 T:1676   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult- plugin returned successfully
15:10:23 T:7720    INFO: CPythonInvoker(29, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): script successfully run
15:10:23 T:7292   DEBUG: Saving fileitems [plugin://plugin.video.hgtv.canada/?mode=GE&name=House%20of%20Bryan&url=64724547710]
15:10:23 T:7292   DEBUG:   -- items: 3, sort method: 0, ascending: false
15:10:23 T:1660  NOTICE: Thread BackgroundLoader start, auto delete: false
15:10:23 T:1660   DEBUG: Thread BackgroundLoader 1660 terminating
15:10:23 T:7720    INFO: Python script stopped
15:10:23 T:7720   DEBUG: Thread LanguageInvoker 7720 terminating
15:10:23 T:7292   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
15:10:25 T:7292   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
15:10:25 T:7292   DEBUG: CInputManager::OnKey: return (0xf00d) pressed, action is Select
15:10:25 T:7292   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.hgtv.canada/?mode=GE&name=Season%203&url=360847427721)
15:10:25 T:7292   DEBUG:   ParentPath = [plugin://plugin.video.hgtv.canada/?mode=GE&name=House%20of%20Bryan&url=64724547710]
15:10:25 T:1676   DEBUG: XFILE::CPluginDirectory::StartScript - calling plugin HGTV Canada('plugin://plugin.video.hgtv.canada/','8','?mode=GE&name=Season%203&url=360847427721')
15:10:25 T:1676   DEBUG: XFILE::CPluginDirectory::WaitOnScriptResult - waiting on the HGTV Canada (id=30) plugin...
15:10:25 T:1740  NOTICE: Thread LanguageInvoker start, auto delete: false
15:10:25 T:1740    INFO: initializing python engine.
15:10:25 T:1740   DEBUG: CPythonInvoker(30, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): start processing
15:10:25 T:1740  NOTICE: -->Python Interpreter Initialized<--
15:10:25 T:1740   DEBUG: CPythonInvoker(30, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): the source file to load is "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py"
15:10:25 T:1740   DEBUG: CPythonInvoker(30, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): setting the Python path to C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada;D:\Program Files (x86)\Kodi\system\python\DLLs;D:\Program Files (x86)\Kodi\system\python\Lib;D:\Program Files (x86)\Kodi\python27.zip;D:\Program Files (x86)\Kodi\system\python\lib\plat-win;D:\Program Files (x86)\Kodi\system\python\lib\lib-tk;D:\Program Files (x86)\Kodi;D:\Program Files (x86)\Kodi\system\python;D:\Program Files (x86)\Kodi\system\python\lib\site-packages
15:10:25 T:1740   DEBUG: CPythonInvoker(30, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): entering source directory C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada
15:10:25 T:1740   DEBUG: CPythonInvoker(30, C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py): instantiating addon using automatically obtained id of "plugin.video.hgtv.canada" dependent on version 2.1.0 of the xbmc.python api
15:10:25 T:7292   DEBUG: ------ Window Init (DialogBusy.xml) ------
15:10:29 T:7292    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to http://www.msftncsi.com (easy=1CA6DFE8, multi=00000000)
15:10:29 T:7292   DEBUG: ------ Window Init (Pointer.xml) ------
15:10:29 T:1740   ERROR: D:\Program Files (x86)\Kodi\system\python\Lib\urllib.py:1288: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              return ''.join(map(quoter, s))
15:10:29 T:1740   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (u'\xa0',)
                                            Traceback (most recent call last):
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py", line 213, in <module>
                                                elif mode=='GE':  getEpisodes(p('url'), p('name'))
                                              File "C:\Users\user\AppData\Roaming\Kodi\addons\plugin.video.hgtv.canada\default.py", line 134, in getEpisodes
                                                u = '%s?url=%s&name=%s&mode=%s' % (sys.argv[0],qp(url), qp(name), mode)
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1293, in quote_plus
                                                s = quote(s, safe + ' ')
                                              File "D:\Program Files (x86)\Kodi\system\python\Lib\urllib.py", line 1288, in quote
                                                return ''.join(map(quoter, s))
                                            KeyError: (u'\xa0',)
                                            -->End of Python script error report<--
15:10:29 T:7292   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
15:10:29 T:1740    INFO: Python script stopped
15:10:29 T:1740   DEBUG: Thread LanguageInvoker 1740 terminating
15:10:29 T:1676   DEBUG:  XFILE::CPluginDirectory::WaitOnScriptResult - plugin exited prematurely - terminating
15:10:29 T:7292   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.hgtv.canada/?mode=GE&name=Season%203&url=360847427721
15:10:29 T:7292   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.hgtv.canada/?mode=GE&name=Season%203&url=360847427721) failed
15:10:29 T:7292   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.hgtv.canada/?mode=GE&name=House%20of%20Bryan&url=64724547710)
15:10:29 T:7292   DEBUG:   ParentPath = [plugin://plugin.video.hgtv.canada/]
15:10:29 T:7292   DEBUG: Loading items: 3, directory: plugin://plugin.video.hgtv.canada/?mode=GE&name=House%20of%20Bryan&url=64724547710 sort method: 0, ascending: false
15:10:29 T:8168  NOTICE: Thread BackgroundLoader start, auto delete: false
15:10:29 T:8168   DEBUG: Thread BackgroundLoader 8168 terminating
15:10:30 T:7292   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
15:10:32 T:7292   DEBUG: CWinEventsWin32::WndProcWindow is active
15:10:32 T:7292   DEBUG: CWinEventsWin32::WndProc: Focus switched to process C:\Program Files (x86)\Notepad++\notepad++.exe
15:10:33 T:4588   DEBUG: CMMNotificationClient::OnPropertyValueChanged: Changed device property of {0.0.0.00000000}.{32b41b58-68e2-493b-8bdb-de3ce3005065} is {9855c4cd-df8c-449c-a181-8191b68bd06c}#0

**Comment by learningit** [comment]
Do not put logs here. Post them to pastebin or xbmclogs. Also if you have issues put them in the kodi forum so that everyone benefits from the answer

**Comment by learningit** [comment]
Fix for unicode issue in V1.0.3

**Comment by 7h3ju57** [comment]
THX!! this fixed it!
