### ISSUE TITLE
Plugin seems broken

### ISSUE THREAD

**Issue by j4n-co** [learningit/plugin.video.hgtv.canada#3]
Hi there, 
It looks like this plugin has recently broke. I'm unable to play any videos, where in the past it worked great. :( 
From the error log: 
`ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403`
`ERROR: CCurlFile::Open failed with code 403 for http://hgtv-vh.akamaihd.net/i/,641/431/ConsumedS1E1005edit.mp4,.csmil/master.m3u8
`

**Comment by learningit** [comment]
Please see the Kodi.org forum http://forum.kodi.tv/showthread.php?tid=232755&pid=2316565#pid2316565
